version: '2'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: proxy
    links:
      - web
    ports:
      - "80:80"
  web:
    build: .
    container_name: web
    entrypoint: /bin/sh /var/www/rails_comfy_docker_app/init.sh
    volumes:
      - /var/www/rails_comfy_docker_app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres


